CONFIG_HOSTNAME=$(basename $(dirname $(realpath ${BASH_SOURCE[0]})))
CONFIG_DEBIAN_RELEASE=buster
CONFIG_BUILD_ARCHS="amd64 riscv64"

#CONFIG_QEMU_VERSIONS="v7.2.0 v7.0.0 v6.0.0 v5.0.0"
#CONFIG_RUN_IN_CONTAINER_BIND_USER=yes
#CONFIG_RUN_SHELL_BIND_HOME=yes
CONFIG_VM_MEM=4G
